feat: sort numbers (#10)
mykytapavlov/python-beginner pull request #63
Opened 2022-12-06 18:06 UTC by KhrystynaTkachyk

Finally)

2022-12-07 09:52 UTC, mykytapavlov requested changes

2022-12-08 06:18 UTC, mykytapavlov commented
Please [squash](https://www.youtube.com/@TheModernCoder/search?query=git) your commits into single one.

2022-12-08 08:16 UTC, KhrystynaTkachyk commented
> Please [squash](https://www.youtube.com/watch?v=V5KrD7CmO4o) your commits into single one.

@mykytapavlov Done.

2022-12-08 11:46 UTC, mykytapavlov approved these changes

2022-12-08 11:46 UTC, merged