Feat/#14 create contact
mykytapavlov/python-beginner pull request #84
Opened 2022-12-08 19:51 UTC by KhrystynaTkachyk

2022-12-09 08:45 UTC, mykytapavlov commented
The change looks good, but now, I'm as a user want to extend requirements! :D
I saw somebody [creates phone book](https://github.com/mykytapavlov/python-beginner/issues/86). I want this program also to store as many contacts as I want. Please extend functionality based on what we have in "creates phone book".

2022-12-10 13:02 UTC, mykytapavlov commented
more technically, `users` dict should store some reference to `i`

2022-12-10 20:03 UTC, KhrystynaTkachyk commented
> more technically, `users` dict should store some reference to `i`

@mykytapavlov Done.

2022-12-12 09:59 UTC, mykytapavlov requested changes

2022-12-12 09:59 UTC, mykytapavlov commented on entry_tasks/14_create_contact/main.py
> +        #print(f'{name}: {phone}')
remove

2022-12-12 09:59 UTC, mykytapavlov commented on entry_tasks/14_create_contact/main.py
> +        counter += 1
Let's assume, loop over users will not print them in the same order as they were inserted (witch is True for the older versions of Python!)
Rework to store `i` somewhere and show it here.

2022-12-13 08:27 UTC, mykytapavlov approved these changes

2022-12-13 08:28 UTC, merged